---
title: "tidyverse-learning-part1"
format: html
editor: visual
---

Learning about tidyverse from datacamp

# Dplyr package

```{r}
# Load the gapminder package
library(gapminder)

# Load the dplyr package
library(dplyr)

# Look at the gapminder dataset
gapminder
```

### Filter

it is like where in sql.

```{r}
# Filter for Afghanistan
gapminder |>
  filter(country == "Afghanistan")

# Filtering all observations that were recorded in 1957
gapminder %>%
    filter(year == 1957)

# Filter for China in 2002
gapminder |>
    filter(year == 2002, country == 'China')
```

### Arrange

Basically sorting. similar to sort by in sql

```{r}
# Sort in ascending order of lifeExp
gapminder |>
    arrange(lifeExp)

# Sort in descending order of lifeExp
gapminder |>
    arrange(desc(lifeExp))

# Filter for the year 1957, then arrange in descending order of population

gapminder |>
    filter(year == 1957) |>
    arrange(desc(pop))
```

### Mutate

mutate would allow you to change existing variable or add a new variable to the dataframe. In here, variable is meaning column name.

```{r}
# Use mutate to change lifeExp to be in months
gapminder |>
    mutate(lifeExp = lifeExp * 12)

# Use mutate to create a new column called lifeExpMonths
gapminder |>
    mutate(lifeExpMonths = lifeExp * 12)

# Filter, mutate, and arrange the gapminder dataset
gapminder |>
    filter(year == 2007) |>
    mutate(lifeExpMonths = lifeExp * 12) |>
    arrange(desc(lifeExpMonths))
```

# ggplot2

```{r}
library(ggplot2)

# Create gapminder_1952
gapminder_1952 <- gapminder |>
  filter(year == 1952)

# Change to put pop on the x-axis and gdpPercap on the y-axis
ggplot(gapminder_1952, aes(x = pop, y = gdpPercap)) +
  geom_point()

# Create a scatter plot with pop on the x-axis and lifeExp on the y-axis
ggplot(gapminder_1952, aes(x = pop, y = lifeExp)) +
  geom_point()
```

### Log Scale

```{r}
# Scatter plot comparing gdpPercap and lifeExp, on x axis by a log a scale
ggplot(gapminder_1952, aes(x = gdpPercap, y = lifeExp)) +
  geom_point() +
  scale_x_log10()

# Scatter plot comparing pop and gdpPercap, with both axes on a log scale
ggplot(gapminder_1952, aes(x = pop, y = gdpPercap)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()
```

### More Aesthetics - size + color

```{r}
# Scatter plot comparing pop and lifeExp, with color representing continent
ggplot(gapminder_1952, aes(x = pop, y = lifeExp, col = continent)) +
  geom_point() +
  scale_x_log10()

# Add the size aesthetic to represent a country's gdpPercap
ggplot(gapminder_1952, aes(x = pop, y = lifeExp, color = continent, size = gdpPercap)) +
  geom_point() +
  scale_x_log10()
```

### Faceting

```{r}
ggplot(gapminder_1952, aes(x = gdpPercap, y = lifeExp)) +
  geom_point() +
  scale_x_log10() +
  facet_wrap(~ continent)
```

```{r}
# Scatter plot comparing gdpPercap and lifeExp, with color representing continent
# and size representing population, faceted by year

ggplot(gapminder, aes(x = gdpPercap, y = lifeExp, col = continent, size = pop)) +
    geom_point() +
    scale_x_log10() +
    facet_wrap(~ year)
```
